services:
  - type: web
    name: bruthus-burger
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    healthCheckPath: /status
    envVars:
      - key: NODE_ENV
        value: production
